project_file: ../capture/projects/otbn_vertical_sca_cw310_keygen
trace_file: null
trace_start: null
trace_end: null
leakage_file: null
save_to_disk: null
save_to_disk_ttest: null
round_select: null
byte_select: null
input_histogram_file: null
output_histogram_file: null
number_of_steps: 1
ttest_step_file: null
plot_figures: true
test_type: "GENERAL_KEY"
mode: otbn
key_len_bytes: 40
sample_start: null
num_samples : null
filter_traces: true
trace_threshold: 1000
trace_db: ot_trace_library
