package(default_visibility = ["//visibility:public"])

load("@//third_party/python:requirements.bzl", "requirement")

py_library(
    name = "data_generator",
    srcs = ["data_generator.py"],
    deps = [requirement("pycryptodome"),],
)