target:
  target_type: chip
  fw_bin: "../objs/sca_ujson_chip_signed.img"
  target_clk_mult: 1
  target_freq: 100000000
  baudrate: 115200
  output_len_bytes: 16
  protocol: "ujson"
  port: "/dev/ttyUSB1"
  usb_serial: "205F355C3236"
fisetup:
  fi_gear: "husky"
  fi_type: "voltage_glitch"
  parameter_generation: "random"
  # Voltage glitch width in cycles.
  glitch_width_min: 5
  glitch_width_max: 150
  glitch_width_step: 3
  # Range for trigger delay in cycles.
  trigger_delay_min: 0
  trigger_delay_max: 500
  trigger_step: 10
  # Number of iterations for the parameter sweep.
  num_iterations: 100
fiproject:
  # Project database type and memory threshold.
  project_db: "ot_fi_project"
  project_mem_threshold: 10000
  # Store FI plot.
  show_plot: True
  num_plots: 10
  plot_x_axis: "trigger_delay"
  plot_x_axis_legend: "[cycles]"
  plot_y_axis: "glitch_width"
  plot_y_axis_legend: "[cycles]"
test:
  which_test: "edn_fi_bus_ack"
  expected_result: '{"result":0,"err_status":0}'
