# This is a basic workflow to run pytest

name: pytest

# Controls when the workflow will run
on:
  # Triggers the workflow on pushes to master and on pull requests (to any branch)
  push:
    branches:
      - master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pytest"
  pytest:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up virtual Python environment
        run: python3 -m venv .venv; source .venv/bin/activate

      - name: Install Python dependencies
        run: python3 -m pip install -U pip "setuptools<66.0.0"; pip install -r python-requirements.txt

      - name: Run pytest
        run: pytest test
