target:
  target_type: chip
  fw_bin: "../objs/sca_ujson_chip_signed.img"
  target_clk_mult: 1
  target_freq: 100000000
  baudrate: 115200
  output_len_bytes: 16
  protocol: "ujson"
  port: "/dev/ttyUSB1"
waverunner:
  waverunner_ip: 100.107.71.10
  num_segments: 20
  # num_samples: 6000
  # offset_samples: 0
  # cycles will only be used if not given in samples
  num_cycles: 60
  offset_cycles: 0
  # sampling rate needed for cycle to sample conversion
  sampling_rate: 2500000000
  channel: C1
  sparsing: 0
capture:
  scope_select: waverunner
  num_traces: 1000
  show_plot: True
  plot_traces: 100
  trace_db: ot_trace_library
  trace_threshold: 10000
  # trace_db: cw
test:
  which_test: aes_random_batch
  # which_test: aes_random
  # which_test: aes_fvsr_key
  # which_test: aes_fvsr_key_batch
  key_len_bytes: 16
  text_len_bytes: 16
  # These initial values are used only for random capture but not fixed-vs-random.
  key_fixed: [0x81, 0x1E, 0x37, 0x31, 0xB0, 0x12, 0x0A, 0x78, 0x42, 0x78, 0x1E, 0x22, 0xB2, 0x5C, 0xDD, 0xF9]
  text_fixed: [0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA]
  key_for_gen: [0x12, 0x34, 0x56, 0x78, 0x9A, 0xBC, 0xDE, 0xF1, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xE0, 0xF0]
  # seed for PRNG to generate sequence of plaintexts and keys; Python random class on host, Mersenne twister implementation on OT SW
  batch_prng_seed: 0
  # 32-bit seed for masking on device. To switch off the masking, use 0 as LFSR seed.
  # lfsr_seed: 0x00000000
  lfsr_seed: 0xdeadbeef
