target:
  target_type: chip
  fw_bin: "../objs/sca_ujson_chip_signed.img"
  target_clk_mult: 1
  target_freq: 100000000
  baudrate: 115200
  output_len_bytes: 16
  protocol: "ujson"
  port: "/dev/ttyUSB1"
waverunner:
  waverunner_ip: 192.168.33.128
  num_segments: 1
  # cycles will only be used if not given in samples
  num_cycles: 100
  # Do not capture 100 nops that are inserted to give the trigger time to rise.
  offset_cycles: 100
  # sampling rate needed for cycle to sample conversion
  sampling_rate: 2500000000
  channel: C1
  sparsing: 0
capture:
  scope_select: waverunner
  num_traces: 101
  show_plot: True
  plot_traces: 20
  trace_db: ot_trace_library
  trace_threshold: 50
test:
  # which_test: ibex_sca_tl_write_batch_fvsr
  # which_test: ibex_sca_tl_write_batch_fvsr_fix_address
  # which_test: ibex_sca_tl_write_batch_random
  # which_test: ibex_sca_tl_write_batch_random_fix_address
  # which_test: ibex_sca_tl_write_fvsr
  # which_test: ibex_sca_tl_write_random
  # which_test: ibex_sca_tl_read_batch_fvsr
  # which_test: ibex_sca_tl_read_batch_fvsr_fix_address
  # which_test: ibex_sca_tl_read_batch_random
  # which_test: ibex_sca_tl_read_batch_random_fix_address
  # which_test: ibex_sca_tl_read_fvsr
  # which_test: ibex_sca_tl_read_random
  # which_test: ibex_sca_register_file_write_batch_fvsr
  # which_test: ibex_sca_register_file_write_batch_random
  # which_test: ibex_sca_register_file_write_fvsr
  # which_test: ibex_sca_register_file_write_random
  # which_test: ibex_sca_register_file_read_batch_fvsr
  # which_test: ibex_sca_register_file_read_batch_random
  # which_test: ibex_sca_register_file_read_fvsr
  which_test: ibex_sca_register_file_read_random
  # seed for PRNG to generate sequence of plaintexts and keys; Python random
  # class on host, Mersenne twister implementation on OT SW.
  batch_prng_seed: 0
