target:
  target_type: cw310
  fpga_bitstream: "../objs/lowrisc_systems_chip_earlgrey_cw310_0.1.bit"
  force_program_bitstream: False
  fw_bin: ../objs/sca_ujson_fpga_cw310.bin
  opentitantool: "../objs/opentitantool"
  # You can specify the port or leave it empty to find it automatically.
  target_clk_mult: 0.24
  target_freq: 24000000
  baudrate: 115200
husky:
  samling_rate: 200000000
  num_cycles: 100
  # Do not capture 100 nops that are inserted to give the trigger time to rise.
  offset_cycles: 100
  scope_gain: 27
capture:
  # scope_select: husky, waverunner, none
  scope_select: husky
  num_segments: 20
  num_traces: 5000
  show_plot: True
  plot_traces: 100
  trace_db: ot_trace_library
  trace_threshold: 10000
test:
  # which_test: ibex_sca_combi_operations_batch_fvsr
  # which_test: ibex_sca_combi_operations_batch
  # which_test: ibex_sca_tl_write_batch_fvsr
  # which_test: ibex_sca_tl_write_batch_fvsr_fix_address
  # which_test: ibex_sca_tl_write_batch_random
  # which_test: ibex_sca_tl_write_batch_random_fix_address
  # which_test: ibex_sca_tl_write
  # which_test: ibex_sca_tl_read_batch_fvsr
  # which_test: ibex_sca_tl_read_batch_fvsr_fix_address
  # which_test: ibex_sca_tl_read_batch_random
  # which_test: ibex_sca_tl_read_batch_random_fix_address
  # which_test: ibex_sca_tl_read
  # which_test: ibex_sca_register_file_write_batch_fvsr
  # which_test: ibex_sca_register_file_write_batch_random
  # which_test: ibex_sca_register_file_write
  # which_test: ibex_sca_register_file_read_batch_fvsr
  # which_test: ibex_sca_register_file_read_batch_random
  # which_test: ibex_sca_register_file_read
  which_test: ibex_sca_register_file_read
  # seed for PRNG to generate sequence of plaintexts and keys; Python random
  # class on host, Mersenne twister implementation on OT SW.
  batch_prng_seed: 0
  core_config: {
    "enable_icache": True,
    "enable_dummy_instr": True,
    "dummy_instr_count": 3,
    "enable_jittery_clock": True,
    "enable_sram_readback": True,
    "enable_data_ind_timing": True,
  }
  sensor_config: {
      "sensor_ctrl_enable": True,
      "sensor_ctrl_en_fatal": [
          False,
          False,
          False,
          False,
          False,
          False,
          False,
          False,
          False,
          False,
          False,
      ],
  }
